name: Instrumented Test

on:
  push:
    branches:
      - 'feature/new_auth_flow'

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 31 ]
        target: [ google_apis ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: instrumentation tests
        run: ./gradlew connectedAndroidTest
        uses: reactivecircus/android-emulator-runner@v2
        if: failure()
        with:
          name: test-report
          path: ${{ github.workspace }}/*/build/reports/
