name: Firebase Instrumentation Tests

on:
  push:
    branches:
      - 'feature/new_auth_flow'

jobs:
  assemble_ui_test_artifacts:
    name: Build artifacts
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build APK for UI test
        run: ./gradlew assembleDebugAndroidTest

      - name: Upload app-debug APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload app-debug-androidTest APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug-androidTest
          path: keyrisdk/build/intermediates/apk/androidTest/debug/keyrisdk-debug-androidTest.apk

  run_ui_tests_on_firebase:
    runs-on: ubuntu-20.04
    needs: assemble_ui_test_artifacts
    steps:
      - uses: actions/checkout@v3
      - name: Download app-debug APK
        uses: actions/download-artifact@v3
        with:
          name: app-debug

      - name: Download app-debug-androidTest APK
        uses: actions/download-artifact@v3
        with:
          name: app-debug-androidTest

      - name: Firebase auth with gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.FIREBASE_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: |
          gcloud firebase test android models list
          gcloud firebase test android run --type instrumentation --app app-debug/app-debug.apk --test app-debug-androidTest/app-debug-androidTest.apk --device model=Pixel6,version=31,locale=en,orientation=portrait --timeout 180s