name: Lint

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: lint
        run: ./gradlew ktlint
      - name: CheckStyle
        run: ./gradlew checkJavaStyle
