name: Add new release

on:
  push:
    branches:
     - main

jobs:
  create_release:
    name: Creating new release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ github.event.head_commit.message }}
