name: Add new release

on:
  push:
    branches:
      - 'releases/**'

jobs:
  create_release:
    name: Creating new release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        env:
          BRANCH: ${{ github.ref_name }}
        with:
          tag: "::set-output name=fragment::${BRANCH##*/}"
